/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, PostAnalytics as PrismaPostAnalytics } from "@prisma/client";

export class PostAnalyticsServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.PostAnalyticsCountArgs, "select">
  ): Promise<number> {
    return this.prisma.postAnalytics.count(args);
  }

  async postAnalyticsItems(
    args: Prisma.PostAnalyticsFindManyArgs
  ): Promise<PrismaPostAnalytics[]> {
    return this.prisma.postAnalytics.findMany(args);
  }
  async postAnalytics(
    args: Prisma.PostAnalyticsFindUniqueArgs
  ): Promise<PrismaPostAnalytics | null> {
    return this.prisma.postAnalytics.findUnique(args);
  }
  async createPostAnalytics(
    args: Prisma.PostAnalyticsCreateArgs
  ): Promise<PrismaPostAnalytics> {
    return this.prisma.postAnalytics.create(args);
  }
  async updatePostAnalytics(
    args: Prisma.PostAnalyticsUpdateArgs
  ): Promise<PrismaPostAnalytics> {
    return this.prisma.postAnalytics.update(args);
  }
  async deletePostAnalytics(
    args: Prisma.PostAnalyticsDeleteArgs
  ): Promise<PrismaPostAnalytics> {
    return this.prisma.postAnalytics.delete(args);
  }
}
